CREATE TABLE authentication_tokens (
	id INT UNSIGNED DEFAULT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	user_id varchar(127) NOT NULL,
	nickname varchar(127) NOT NULL,
	data text NOT NULL,
	creation_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	last_use_date TIMESTAMP NOT NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
	not_before TIMESTAMP DEFAULT NULL,
	not_after TIMESTAMP DEFAULT NULL
);
